#!ruby -Ks

module Romaji
 def to_Hiragana(inputed)
   re = nil
   case inputed
   when "a","A"
     re = "‚ "
   when "i","I", "yi","YI","wi","WI"
     re = "‚¢"
   when "u","U","wu","WU"
     re = "‚¤"
   when "e","E","ye","YE","we","WE"
     re = "‚¦"
   when "o","O"
     re = "‚¨"
   when "ka" , "ca", "KA","CA"
     re = "‚©"
   when "ki","KI"
     re = "‚«"
   when "ku" , "cu","KU","CU"
     re = "‚­"
   when "ke","KE"
     re = "‚¯"
   when "ko" , "co","KO","CO"
     re = "‚±"
   when "sa","SA"
     re = "‚³"
   when "si" , "ci", "SI", "CI"
     re = "‚µ"
   when "su", "SU"
     re = "‚·"
   when "se" , "ce", "SE", "CE"
     re = "‚¹"
   when "so", "SO"
     re = "‚»"
   when "ta", "TA"
     re = "‚½"
   when "ti", "chi", "TI", "CHI"
     re = "‚¿"
   when "tu", "tsu", "TU", "TSU"
     re = "‚Â"
   when "te", "TE"
     re = "‚Ä"
   when "to", "TO"
     re = "‚Æ"
   when "na", "NA"
     re = "‚È"
   when "ni", "NI"
     re = "‚É"
   when "nu", "NU"
     re = "‚Ê"
   when "ne", "NE"
     re = "‚Ë"
   when "no", "NO"
     re = "‚Ì"
   when "ha", "HA"
     re = "‚Í"
   when "hi", "HI"
     re = "‚Ð"
   when "hu" , "fu", "HU", "FU"
     re = "‚Ó"
   when "he", "HE"
     re = "‚Ö"
   when "ho", "HO"
     re = "‚Ù"
   when "ma", "MA"
     re = "‚Ü"
   when "mi", "MI"
     re = "‚Ý"
   when "mu", "MU"
     re = "‚Þ"
   when "me", "ME"
     re = "‚ß"
   when "mo", "MO"
     re = "‚à"
   when "ya", "YA"
     re = "‚â"
   when "yu", "YU"
     re = "‚ä"
   #when "ye", ""
   #  re = "‚¢‚¥"
   when "yo", "YO"
     re = "‚æ"
   when "ra", "RA"
     re = "‚ç"
   when "ri", "RI"
     re = "‚è"
   when "ru", "RU"
     re = "‚é"
   when "re", "RE"
     re = "‚ê"
   when "ro", "RO"
     re = "‚ë"
   when "wa", "WA"
     re = "‚í"
   #when "wi"
   #  re = "‚¤‚¡"
   #when "we"
   #  re = "‚¤‚¥"
   when "wo","WO"
     re = "‚ð"
   when "ga"
     re = "‚ª"
   when "gi"
     re = "‚¬"
   when "gu"
     re = "‚®"
   when "ge"
     re = "‚°"
   when "go"
     re = "‚²"
   when "za"
     re = "‚´"
   when "zi" , "ji"
     re = "‚¶"
   when "zu"
     re = "‚¸"
   when "ze"
     re = "‚º"
   when "zo"
     re = "‚¼"
   when "da"
     re = "‚¾"
   when "di"
     re = "‚À"
   when "du"
     re = "‚Ã"
   when "de"
     re = "‚Å"
   when "do"
     re = "‚Ç"
   when "ba"
     re = "‚Î"
   when "bi"
     re = "‚Ñ"
   when "bu"
     re = "‚Ô"
   when "be"
     re = "‚×"
   when "bo"
     re = "‚Ú"
   when "pa"
     re = "‚Ï"
   when "pi"
     re = "‚Ò"
   when "pu"
     re = "‚Õ"
   when "pe"
     re = "‚Ø"
   when "po"
     re = "‚Û"
   when "xa" , "la"
     re = "‚Ÿ"
   when "xi" , "li"
     re = "‚¡"
   when "xu" , "lu"
     re = "‚£"
   when "xe" , "le"
     re = "‚¥"
   when "lya", "xya"
     re = "‚á"
   when "lyu", "xyu"
     re = "‚ã"
   when "lyo", "xyo"
     re = "‚å"
   when "xo" , "lo"
     re = "‚§"
   when "kya"
     re = "‚«‚á"
   when "kyi"
     re = "‚«‚¡"
   when "kyu"
     re = "‚«‚ã"
   when "kye"
     re = "‚«‚¥"
   when "kyo"
     re = "‚«‚å"
   when "sya" , "sha"
     re = "‚µ‚á"
   when "syi"
     re = "‚µ‚¡"
   when "syu", "shu"
     re = "‚µ‚ã"
   when "sye", "she"
     re = "‚µ‚¥"
   when "syo", "sho"
     re = "‚µ‚å"
   when "tya","cha"
     re = "‚¿‚á"
   when "tyi"
     re = "‚¿‚¡"
   when "tyu", "chu"
     re = "‚¿‚ã"
   when "tye", "che"
     re = "‚¿‚¥"
   when "tyo", "cho"
     re = "‚¿‚å"
   when "nya"
     re = "‚É‚á"
   when "nyu"
     re = "‚É‚ã"
   when "nyo"
     re = "‚É‚å"
   when "hya"
     re = "‚Ð‚á"
   when "hyu"
     re = "‚Ð‚ã"
   when "hyo"
     re = "‚Ð‚å"
   when "mya"
     re = "‚Ý‚á"
   when "myu"
     re = "‚Ý‚ã"
   when "myo"
     re = "‚Ý‚å"
   when "rya"
     re = "‚è‚á"
   when "ryu"
     re = "‚è‚ã"
   when "ryo"
     re = "‚è‚å"
   when "gya"
     re = "‚¬‚á"
   when "gyu"
     re = "‚¬‚ã"
   when "gyo"
     re = "‚¬‚å"
   when "zya", "ja"
     re = "‚¶‚á"
   when "zyi"
     re = "‚¶‚¡"
   when "zyu", "ju"
     re = "‚¶‚ã"
   when "zye", "je"
     re = "‚¶‚¥"
   when "zyo", "jo"
     re = "‚¶‚å"
   when "dya"
     re = "‚À‚á"
   when "dyi"
     re = "‚À‚¡"
   when "dyu"
     re = "‚À‚ã"
   when "dye"
     re = "‚À‚¥"
   when "dyo"
     re = "‚À‚å"
   when "bya"
     re = "‚Ñ‚á"
   when "byi"
     re = "‚Ñ‚¡"
   when "byu"
     re = "‚Ñ‚ã"
   when "bye"
     re = "‚Ñ‚¥"
   when "byo"
     re = "‚Ñ‚å"
   when "pya"
     re = "‚Ò‚á"
   when "pyi"
     re = "‚Ò‚¡"
   when "pyu"
     re = "‚Ò‚ã"
   when "pye"
     re = "‚Ò‚¥"
   when "pyo"
     re = "‚Ò‚å"
   when "fa"
     re = "‚Ó‚Ÿ"
   when "fi"
     re = "‚Ó‚¡"
   when "fe"
     re = "‚Ó‚¥"
   when "fo"
     re = "‚Ó‚§"
   when "tha"
     re = "‚Ä‚á"
   when "thi"
     re = "‚Ä‚¡"
   when "thu"
     re = "‚Ä‚ã"
   when "the"
     re = "‚Ä‚¥"
   when "tho"
     re = "‚Ä‚å"
   when "dha"
     re = "‚Å‚á"
   when "dhi"
     re = "‚Å‚¡"
   when "dhu"
     re = "‚Å‚ã"
   when "dhe"
     re = "‚Å‚¥"
   when "dho"
     re = "‚Å‚å"
   when "ltu", "xtu", "ltsu", "xtsu"
     re = "‚Á"
     @former_st = ""
   end
   return re
 end
end
